#!/usr/bin/env bash

# Configures a new Ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string
# Configure redirection from /redirect_me to another page with a 301 status


# Update and install Nginx
echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Start nginx service
sudo service nginx start

# Allow Nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Configure redirection from /redirect_me to another page with a 301 status
sudo sed -i '/location \/ {/a \       location /redirect_me { \n               return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \n       }' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart

echo -e "\nCompleted.\n"

