#!/usr/bin/env bash
# Bash script that creates an RSA key pair.
# Name of the created private key must be school
# Number of bits in the created key to be created 4096
# The created key is protected by the passphrase betty
# Generate RSA key pair
key_name="school"
ssh-keygen -t rsa -b 4096 -f "$key_name" -N "betty"
